config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  path_names: {sign_in: "login", sign_out: "logout"},controllers: {omniauth_callbacks: "authentications"}
  root 'default#index'
  

  resources :compromissos
  
  get 'nosotros/informacion'
  post'articles/new'
  get 'welcome/index'

  resources :nosotros
  resources :articles
  resources :fotografos

  
  

end

app/models/fotografo.rb
class Fotografo < ActiveRecord::Base
	 has_many :compromisso 

	 has_attached_file :image
	 validates :image, :attachment_presence => true
	
	 validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	 # Validate filename
	 validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
	 # Explicitly do not validate
	 do_not_validate_attachment_file_type :image

	
end

app/controllers/fotografos_controller.rb
class FotografosController < ApplicationController
	before_action :set_fotografo, only:[:show,:edit, :update , :destroy]

	def index
    	@fotografo=Fotografo.all
  	end

	def edit
    end

    def update
	    @fotografo = Fotografo.find(params[:id])
	 
	    if @fotografo.update(article_params)
	      redirect_to @fotografo
	    else
	      render 'edit'
	    end
	end

    def destroy
    	@fotografo.destroy
 
  		redirect_to fotografos_path
    end
    
    def edit
    end
	
	def new
		@fotografo=Fotografo.new
	end

	def create
		@fotografo=Fotografo.new(article_params)

  		@fotografo.save
  		redirect_to @fotografo
	end

	def show
	end

	private
	  def set_fotografo
	  	@fotografo=Fotografo.find(params[:id])
	  end

	  def article_params
	  	## aqui se define los atributos que seran utilizados por seguridad
	    params.require(:fotografo).permit(:image,:nombre_pila,:apellido,:telefono,:fecha_nacimiento,:rut,:email,:comentarios)
	  	
	  
	  end

end

app/helpers/fotografos_helper.rb
module FotografosHelper
end

app/views/fotografos/edit.html.erb
<h1>Editando fotografo</h1>
 
<%= form_for :fotografo, html: { multipart: true } ,url: fotografo_path(@fotografo), method: :patch do |f| %>
  <% if @fotografo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@fotografo.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @fotografo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
 <p id="pe">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <p id="pe">
    <%= f.label :nombre_pila %><br>
    <%= f.text_field :nombre_pila %>
  </p>
  <p id="pe">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </p>
  <p id="pe">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </p>
  <p id="pe">
    <%= f.label :fecha_nacimiento %><br>
    <%= f.text_field :fecha_nacimiento %>
  </p>
  <p id="pe">
    <%= f.label :rut %><br>
    <%= f.text_field :rut %>
  </p>
  <p id="pe">
    <%= f.label :email %><br>
    <%= f.text_field  :email %>
  </p>
 
  <p id="pe">
    <%= f.label :comentarios %><br>
    <%= f.text_area  :comentarios %>
  </p>




      
      
  
      
     
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<!--fotografo_path nos redirige al show del @fotografo-->
<!--fotografos_path nos redirige a los fotografos tabla-->
<%= link_to 'atras', fotografo_path %>

app/views/fotografos/index.html.erb
<% @fotografo.each do |f| %>
  <tr>
    <td><%= f.nombre_pila %></td>
    <td><%= f.fecha_nacimiento %></td>
    <td><%= link_to 'Show', fotografo_path(f) %></td>
    <td><%= link_to 'Edit', edit_fotografo_path(f) %></td>
    <td><%= link_to 'Destroy', fotografo_path(f),
                    method: :delete, data: { confirm: 'Esta seguro?' } %></td>
    </br>
  </tr>
<% end %>
</table>

app/views/fotografos/show.html.erb
<div class="my-skills text-center">
	<div class="container">
		<h3 >Profesional</h3>
		<div class="strip text-center"><%= image_tag("icons/tuerca.png")%> </div>


		<div class="skill-grids">
					<div class="col-md-1 skills-grid alaizq">
						<div class="circle" id="circles-1"></div>
						<p id="pe">Photoshop</p>
					</div>
					<div class="col-md-2 skills-grid alaizq">
						<div class="circle" id="circles-2"></div>
						<p id="pe">Illustrator</p>
					</div>
					

					<div class="clearfix"> </div>
				 <%= javascript_include_tag 'circles', :type => 'text/javascript' %>
				 <!--<script type="text/javascript" src="assets/javascripts/circles.js"></script>-->
					         <script>
								var colors = [
										['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff']
									];
								for (var i = 1; i <= 7; i++) {
									var child = document.getElementById('circles-' + i),
										percentage = 20 + (i * 20);
										
									Circles.create({
										id:         child.id,
										percentage: percentage,
										radius:     80,
										width:      10,
										number:   	percentage / 1,
										text:       '%',
										colors:     colors[i - 1]
									});
								}
							
							</script>
							
		</div>
	</div>	
</div>








</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

</br>
</br>
</br>
</br>
</br>
<%= image_tag(@fotografo.image.url, size: "80x160" )%>
</br>

<%= @fotografo.nombre_pila %>
</br>
<%= @fotografo.fecha_nacimiento %>
</br>
<%= select_tag "favorite_color", '<option value="red">Red</option><option value="green">Green</option><option value="blue">Blue</option>'.html_safe %> 

</br>
<%= link_to 'Fotografos', fotografos_path %>
</br>
<%= link_to 'Compromiso',:controller => "compromissos" ,action: "index" ,:searchbox=> @fotografo.nombre_pila %>