config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  path_names: {sign_in: "login", sign_out: "logout"},controllers: {omniauth_callbacks: "authentications"}
  root 'default#index'
  

  resources :compromissos
  
  get 'nosotros/informacion'
  post'articles/new'
  get 'welcome/index'

  resources :nosotros
  resources :articles
  resources :fotografos

  
  

end

app/models/compromisso.rb
class Compromisso < ActiveRecord::Base
	belongs_to :fotografo # compromisso tendra fotografo_id
	belongs_to :servicio 

	 # busqueda por texto

	 def self.search(search)

		 if search 
		 	
		 	
		   Compromisso.joins(:fotografo).where('nombre_pila LIKE ?', "%#{search}%")

		 

		 end

	end
end

app/controllers/compromissos_controller.rb
class CompromissosController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource
  
  before_action :set_compromisso, only: [:show,:edit, :update, :destroy]

  # GET /compromissos
  # GET /compromissos.json
  def index
    #inicio compromisso para tenerlo listo en index
    @compromisso = Compromisso.new
    if params[:searchbox]
        #@products = Product.search(params[:searchbox])
        @compromissos = Compromisso.search(params[:searchbox])
        #@compromissos = Compromisso.all
        @date = params[:month] ? Date.parse(params[:month]) : Date.today
    else

  
        @compromissos = Compromisso.all
        @date = params[:month] ? Date.parse(params[:month]) : Date.today
    end
  end

  # GET /compromissos/1
  # GET /compromissos/1.json
  def show

  end
  

  # GET /compromissos/new
  def new
    @compromisso = Compromisso.new
  end

  # GET /compromissos/1/edit
  def edit
  end

  # POST /compromissos
  # POST /compromissos.json
  def create
    @compromisso = Compromisso.new(compromisso_params)

    respond_to do |format|
      if @compromisso.save
        format.html { redirect_to @compromisso, notice: 'Compromiso ha sido guardado con exito' }
        format.json { render :show, status: :created, location: @compromisso }
      else
        format.html { render :new }
        format.json { render json: @compromisso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compromissos/1
  # PATCH/PUT /compromissos/1.json
  def update
    respond_to do |format|
      if @compromisso.update(compromisso_params)
        format.html { redirect_to @compromisso, notice: 'Compromiso a sido actualizado con exito' }
        format.json { render :show, status: :ok, location: @compromisso }
      else
        format.html { render :edit }
        format.json { render json: @compromisso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compromissos/1
  # DELETE /compromissos/1.json
  def destroy
    @compromisso.destroy
    respond_to do |format|
      format.html { redirect_to compromissos_url, notice: 'Compromiso a sido eliminado con exito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compromisso
      @compromisso = Compromisso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compromisso_params
      params.require(:compromisso).permit(:titulo, :texto, :date, :servicio_id, :fotografo_id)
    end
end

app/helpers/compromissos_helper.rb
module CompromissosHelper
end

app/views/compromissos/_form.html.erb
<%= form_for(@compromisso) do |f| %>
  <% if @compromisso.errors.any? %>
    <div id="error_explanation">
      <h2 id="pe"><%= pluralize(@compromisso.errors.count, "error") %> prohibited this compromisso from being saved:</h2>

      <ul>
      <% @compromisso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :Nombre_Evento  %><br>
    <%= f.text_field :titulo %>
  </div>
  </br>
  <div class="field">
  <%= f.label :Fotografo  %><br>
  <%= f.collection_select(:fotografo_id, Fotografo.all,:id, :nombre_pila,  {:prompt => :nombre_pila})%>
  </div>
  <div class="field">
  <%= f.label :Servicio  %><br>
                      <!-- nombre del campo, de donde saca la info , que quiere sacar de la info-->
  <%= f.collection_select(:servicio_id, Servicio.all,:id, :nombre,  {:prompt => "Seleccione Servicio"})%>
  </div>
  </br>
  <div class="field">
    <%= f.label :dato %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compromissos/edit.html.erb
<h1>Editing Compromisso</h1>

<%= render 'form' %>

<%= link_to 'Show', @compromisso %> |
<%= link_to 'Back', :controller => "compromissos" ,action: "index" ,:searchbox=> @compromisso.fotografo.nombre_pila %>

app/views/compromissos/index.html.erb
         <!--<script type="text/javascript" src="assets/javascripts/circles.js"></script>-->

<section class="compromiso-us" id="compromiso-us">
  <%= javascript_include_tag 'compromissos', :type => 'text/javascript' %>

  <div class="content" >
  
    <h1>Lapsus Photos</h1>
    <hr/>
    <p class="title" style="color:white">Lapsus es una empresa dedicada a la captura de los momentos</p>
      <section class="portafolio-compromiso" id="portafolio-compromiso">


      <div class="portafolio-compromiso-margin">
      
  
</div>   
         
      </section>
      <p></p>
  </div>
 
  </section>
      
<section class="portfolio" id="portfolio">


    <div class="portfolio-margin">





<%= javascript_include_tag 'compromissos', :type => 'text/javascript' %>



<!--fotografo_path nos redirige al show del @fotografo -->





<p id="notice"><%= notice %></p>

<h1 id="pe">Listando Compromisos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Fotografo</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compromissos.each do |compromisso| %>
      <tr>
        <td><%= compromisso.titulo %></td>
        <td><%= compromisso.fotografo.nombre_pila %></td>
        <td><%= compromisso.date %></td>
        <td><%= link_to 'Mostrar', compromisso %></td>
        <td> <% if user_signed_in? %><%= link_to 'Editar', edit_compromisso_path(compromisso) %><% end %></td>
        <td> <% if can? :destroy, compromisso %><%= link_to 'Eliminar', compromisso, method: :delete, data: { confirm: 'Esta seguro?' } %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'nuevo compromiso', new_compromisso_path(@compromissos.all.map { |x| x }.first) %>

<div id="calendar">
  <h2 id="month">
    <p id="pe"><input type="button" value="Peticion de servicio" onclick="mostrar()" style="font-size:14px;cursor:pointer;margin:15px;padding:5px;"/> </p>
    <p id="pe">Fotografo <%= @compromissos.all.map { |x| x.fotografo.nombre_pila }.first %> </p>
    
    
    
    
    

    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d"), :controller => "compromissos" ,action: "index" , :searchbox=> @compromissos.all.map { |x| x.fotografo.nombre_pila }.first  %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d"), :controller => "compromissos" ,action: "index" , :searchbox=> @compromissos.all.map { |x| x.fotografo.nombre_pila }.first %>
    
  </h2>
  <%= calendar_for @compromissos, :year => @date.year, :month => @date.month do |t| %>
  <%= t.head('DOMINGO','LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO') %>
  <%= t.day do |day, compromissos| %>
  <%= day.day %>
  <% compromissos.each do |compromisso| %><br>
  <%= link_to h(compromisso.fotografo.nombre_pila), compromisso %><br>
  <%= link_to 'Editar', edit_compromisso_path(compromisso) %> | <%= link_to 'Deletar', compromisso, method: :delete, data: { confirm: 'Esta seguro?' } %>
  <% end %>
  <% end %>
  <% end %>
</div>
<%= link_to 'Nuevo comprosimo', new_compromisso_path %>



















































<script type="text/javascript">

function mostrar(){
document.getElementById('ventana-flotante').style.display = 'block';}
</script>






<div id='ventana-flotante' >

   <a class='cerrar' href='javascript:void(0);' id="ocultar">x</a>

   <div id='contenedor'>

       <div class='contenido'>

<%= form_for(@compromisso) do |f| %>
  <% if @compromisso.errors.any? %>
    <div id="error_explanation">
      <h2 id="pe"><%= pluralize(@compromisso.errors.count, "error") %> prohibited this compromisso from being saved:</h2>

      <ul>
      <% @compromisso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :Nombre_Evento  %><br>
    <%= f.text_field :titulo %>
  </div>
  </br>
  <div class="field">
    <%= f.label :Texto  %><br>
    <%= f.text_field :texto %>
  </div>
  </br>
  <div class="field">
  <%= f.label :Fotografo  %><br>
  <%= f.collection_select(:fotografo_id,
                          Fotografo.find(@compromissos.all.map { |x| x.fotografo}),
                          :id,
                          :nombre_pila,  
                          {:prompt => "Seleccione"})%>
  </div>
  <div class="field">
  <%= f.label :Servicio  %><br>
                      <!-- nombre del campo, de donde saca la info , que quiere sacar de la info-->
  <%= f.collection_select(:servicio_id, Servicio.all,:id, :nombre,  {:prompt => "Seleccione Servicio"})%>
  </div>
  </br>
  <div class="field">
    <%= f.label :dato %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



      
       </div>

   </div>

</div>

</section>
</div>

app/views/compromissos/new.html.erb
<h1>New Compromisso</h1>

<%= render 'form' %>

<%= link_to 'Back', compromissos_path %>

app/views/compromissos/show.html.erb
<p id="notice"><%= notice %></p>

<p id="pe">
  <strong>Titulo:</strong>
  <%= @compromisso.titulo %>
</p>

<p id="pe">
  <strong>Texto:</strong>
  <%= @compromisso.servicio.nombre %>
</p>

<p id="pe">
  <strong>Date:</strong>
  <%= @compromisso.date %>
</p>


<%= link_to 'Edit', edit_compromisso_path(@compromisso) %> |
<%= link_to 'Back',:controller => "compromissos" ,action: "index" ,:searchbox=> @compromisso.fotografo.nombre_pila %>